-- MySQL Script generated by MySQL Workbench
-- Mon Feb 19 18:51:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Table `mydb`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `files` (
  `idfile` INT NOT NULL,
  `hash` VARCHAR(255) NULL,
  PRIMARY KEY (`idfile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modules` (
  `idmodules` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`idmodules`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apis` (
  `idapis` INT NOT NULL,
  `module` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idapis`),
  INDEX `module_idx` (`module` ASC),
  CONSTRAINT `module`
    FOREIGN KEY (`module`)
    REFERENCES `modules` (`idmodules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`extract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `extract` (
  `idextract` INT NOT NULL,
  `hash` INT NULL,
  `api` INT NULL,
  `call_number` INT NULL,
  PRIMARY KEY (`idextract`),
  INDEX `hash_idx` (`hash` ASC),
  INDEX `api_idx` (`api` ASC),
  CONSTRAINT `hash`
    FOREIGN KEY (`hash`)
    REFERENCES `files` (`idfile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `api`
    FOREIGN KEY (`api`)
    REFERENCES `apis` (`idapis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

